server:
  port: 3000

spring:
  datasource:
    url: xxxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxxxxxxxxxxxx
    password: xxxxxxxxxxxxxxxxxxxxx

logging:
  level:
    com.shihui: debug

tencent:
  appId: xxxxxxxxxxxxxxxxxxxxxx
  secretId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  secretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  region: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  photoBucket: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
