server:
  port: 3000

spring:
  datasource:
    url: xxxxxxxxxxxxxxxxxxx
    username: xxxxxxxxxxxx
    password: xxxxxxxxxxxxx

logging:
  level:
    com.shihui: debug

tencent:
  appId: xxxxxxxxxxxxxx
  secretId: xxxxxxxxxxxxx
  secretKey: xxxxxxxxxxxxxx
  region: xxxxxxxxxxxx
  photoBucket: xxxxxxxxxxxxx



